### ISSUE TITLE
Harmonization of Installation Process

### ISSUE THREAD

**Issue by alexanderkaiser** [eclipse/iottestware#4]
Merge the existing install scripts and harmonize the installation process for all Test Suites as proposed via the [mailing list](https://dev.eclipse.org/mhonarc/lists/iottestware-dev/msg00018.html)

**Comment by kretzschi** [comment]
@alexanderkaiser the only thing missing would be introducing tpd's into the install script.

**Comment by kretzschi** [comment]
It seems this issue is already done. If so, please close it.
